server:
  port: 8082

spring:
  application:
    name: housekeeping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelos_housekeeping
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
